### ISSUE TITLE
Missing step under "3. In the new repository, turn on GitHub Pages:"

### ISSUE THREAD

**Issue by ElizabethFernandes** [ubc-library-rc/rc-workshop-template#13]
At []https://ubc-library-rc.github.io/rc-workshop-template/#set-up-the-rc-workshop-site , step 3, the repository has to be public in order to turn on GitHub pages. Maybe we can mention somewhere earlier in the process that we should create it as a public repository instead of private, or just add a "in case you can't see the source option, scroll down to the danger zone, click on "change repository visibility" and select "make public"?

**Comment by JeremyBuhler** [comment]
Hi @ElizabethFernandes, good point. Public is the default setting in step 1 so a user shouldn't encounter this problem unless they actively change it to "private," but I'll add a note in step 1 to make this clear.

**Comment by JeremyBuhler** [comment]
Resolved with [https://github.com/ubc-library-rc/rc-workshop-template/commit/a583b2b4143c55130ad5368949522c25fb9808aa](https://github.com/ubc-library-rc/rc-workshop-template/commit/a583b2b4143c55130ad5368949522c25fb9808aa)
